"use client";
import {useState} from "react";
import {fundProspectusCase} from "../lib/fund-prospectus";

export default function FundProspectusLab(){
 const [result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function run(){setLoading(true);setError("");try{const r=await fetch("/api/evaluate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({state:fundProspectusCase.judgmentState+fundProspectusCase.excerpt,questions:fundProspectusCase.questions})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Request failed");setResult(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const answers=result?.result?.answers||{};const choice=(id:string)=>answers[id]?.choice||"—";const conf=(id:string)=>{const a=answers[id];if(!a)return"";const p=a.probabilities?.[a.choice];return typeof p==="number"?Math.round(p*100)+"%":""};
 return <section className="fundLab"><div className="deepIntro"><div className="eyebrow">FINANCIAL SERVICES · RAW PROSPECTUS → REGULATORY GRAPH</div><h2>Start with the document, not a pre-built entity list</h2><p>The input is only prospectus text plus the questions we need answered. Jev must resolve the named legal entities from that evidence; the application then materialises the returned role assignments as graph edges.</p></div>
 <div className="fundFlow"><div><small>01 · INPUT</small><b>Raw prospectus text</b><span>no extracted entity payload</span></div><i>→</i><div className="jevLayer"><small>02 · JEV</small><b>Bounded role questions</b><span>entity + confidence</span></div><i>→</i><div><small>03 · VALIDATE</small><b>Evidence / threshold</b><span>review uncertain links</span></div><i>→</i><div><small>04 · GRAPH</small><b>Typed relationships</b><span>assessment input</span></div></div>
 <div className="prospectusExcerpt"><small>ONLY MODEL EVIDENCE · SYNTHETIC PROSPECTUS EXCERPT</small><p>{fundProspectusCase.excerpt}</p></div>
 <div className="fundContract"><div><small>REQUEST · STATE</small><h3>1 raw evidence string</h3><pre>{fundProspectusCase.judgmentState+fundProspectusCase.excerpt}</pre></div><div><small>REQUEST · QUESTIONS</small><h3>{fundProspectusCase.questions.length} typed Choice judgments</h3>{fundProspectusCase.questions.map(q=><div className="questionSpec" key={q.id}><b>{q.id}</b><span>{q.instructions}</span><small>allowed choices: {Object.keys(q.criteria||{}).join(" · ")}</small></div>)}</div></div>
 <button className="run" onClick={run} disabled={loading}>{loading?"Reading prospectus…":"Run prospectus analysis →"}</button>{error&&<div className="error">{error}</div>}
 {result&&<><div className="jevRawResponse"><small>JEV RESPONSE · WHAT CAME BACK</small><div className="responseMeta"><span>latency <b>{result.latencyMs} ms</b></span><span>answers <b>{Object.keys(answers).length}</b></span></div>{Object.entries(answers).map(([id,a]:any)=><div className="responseAnswer" key={id}><div><b>{id}</b><strong>{a.choice??"—"}</strong></div><div className="probList">{a.probabilities&&Object.entries(a.probabilities).sort((x:any,y:any)=>Number(y[1])-Number(x[1])).map(([label,p]:any)=><span key={label}><i style={{width:Math.round(Number(p)*100)+"%"}}/><em>{label}</em><b>{Math.round(Number(p)*100)}%</b></span>)}</div></div>)}</div><div className="graphHead"><div><small>REGULATORY ENTITY GRAPH</small><h3>Relationships resolved directly from document evidence</h3></div><span>{result.latencyMs} ms</span></div><div className="graph">{fundProspectusCase.graphRows.map(g=><div className="edge" key={g.question}><span className="node">{g.from}</span><b>— {g.relation} →</b><span className="node target">{choice(g.question)}</span><small>{conf(g.question)}</small></div>)}</div><div className="boundary"><b>Application transformation</b><p>JEV does not return this graph. The UI takes each typed answer (for example <code>depositary → Continental Depositary Bank S.A.</code>) and materialises a domain edge. The probabilities remain attached as provenance/confidence metadata rather than being collapsed into the graph fact.</p></div><div className="assessment"><h3>FI assessment hand-off</h3><p>Persist the source document, question, returned choice and probabilities. Low-confidence or contradictory links go to accountable review; accepted links can feed KYC/AML, delegation, custody and jurisdiction assessments.</p></div></>}
 </section>
}