"use client";
import {useState} from "react";
import {fundProspectusCase} from "../lib/fund-prospectus";

export default function FundProspectusLab(){
 const [result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function run(){setLoading(true);setError("");try{const r=await fetch("/api/evaluate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({state:fundProspectusCase.judgmentState+fundProspectusCase.excerpt,questions:fundProspectusCase.questions})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Request failed");setResult(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const answers=result?.result?.answers||{};const choice=(id:string)=>answers[id]?.choice||"—";const conf=(id:string)=>{const a=answers[id];if(!a)return"";const p=a.probabilities?.[a.choice];return typeof p==="number"?Math.round(p*100)+"%":""};
 return <section className="fundLab"><div className="deepIntro"><div className="eyebrow">FINANCIAL SERVICES · RAW PROSPECTUS → REGULATORY GRAPH</div><h2>Start with the document, not a pre-built entity list</h2><p>The input is only prospectus text plus the questions we need answered. Jev must resolve the named legal entities from that evidence; the application then materialises the returned role assignments as graph edges.</p></div>
 <div className="fundFlow"><div><small>01 · INPUT</small><b>Raw prospectus text</b><span>no extracted entity payload</span></div><i>→</i><div className="jevLayer"><small>02 · JEV</small><b>Bounded role questions</b><span>entity + confidence</span></div><i>→</i><div><small>03 · VALIDATE</small><b>Evidence / threshold</b><span>review uncertain links</span></div><i>→</i><div><small>04 · GRAPH</small><b>Typed relationships</b><span>assessment input</span></div></div>
 <div className="prospectusExcerpt"><small>ONLY MODEL EVIDENCE · SYNTHETIC PROSPECTUS EXCERPT</small><p>{fundProspectusCase.excerpt}</p></div>
 <div className="boundary"><b>What is supplied to Jev?</b><p>The raw excerpt above and five bounded questions such as “Which legal entity is explicitly appointed depositary?”. There is no separate extracted-facts object or candidate-entity list in the state.</p></div>
 <button className="run" onClick={run} disabled={loading}>{loading?"Reading prospectus…":"Run prospectus analysis →"}</button>{error&&<div className="error">{error}</div>}
 {result&&<><div className="graphHead"><div><small>REGULATORY ENTITY GRAPH</small><h3>Relationships resolved directly from document evidence</h3></div><span>{result.latencyMs} ms</span></div><div className="graph">{fundProspectusCase.graphRows.map(g=><div className="edge" key={g.question}><span className="node">{g.from}</span><b>— {g.relation} →</b><span className="node target">{choice(g.question)}</span><small>{conf(g.question)}</small></div>)}</div><div className="assessment"><h3>FI assessment hand-off</h3><p>Persist the source document, question, returned choice and probabilities. Low-confidence or contradictory links go to accountable review; accepted links can feed KYC/AML, delegation, custody and jurisdiction assessments.</p></div></>}
 </section>
}