"use client";
import {useState} from "react";
import {pipeline} from "@huggingface/transformers";
import {Question} from "../lib/types";

const MODEL="onnx-community/gemma-3-270m-it-ONNX";
const cases=[
 {id:"release",title:"Release gate",text:"Production change CHG-104 has completed testing, has rollback automation, no unresolved critical findings, and all mandatory approvers signed.",labels:["APPROVE","REVIEW","BLOCK"],expected:"APPROVE"},
 {id:"kyc",title:"KYC discrepancy",text:"Customer onboarding evidence contains an ownership mismatch between the registry extract and the declaration. No investigator has resolved it.",labels:["CLEAR","REVIEW","BLOCK"],expected:"REVIEW"},
 {id:"api",title:"API boundary",text:"The proposed API combines customer master-data mutation, securities-order execution and HR payroll operations behind one service boundary.",labels:["COHESIVE","REVIEW","POOR_BOUNDARY"],expected:"POOR_BOUNDARY"},
 {id:"authority",title:"Agent authority",text:"An autonomous agent proposes a EUR 2.4m supplier commitment. Its delegated authority permits commitments only up to EUR 250k; no human approver has authorized an exception.",labels:["EXECUTE","REVIEW","BLOCK"],expected:"BLOCK"}
];
const makeQuestion=(c:any):Question=>({id:"outcome",type:"choice",instructions:"Choose exactly one outcome supported by the evidence.",criteria:Object.fromEntries(c.labels.map((label:string)=>[label,"Select only when the evidence supports "+label+"."]))} as Question);
const parseGemma=(raw:string,labels:string[])=>labels.find(label=>raw.toUpperCase().includes(label))||raw.trim().split(/\\s/)[0].replace(/[^A-Z_]/gi,"").toUpperCase();
export default function GemmaBenchmark(){
 const[loading,setLoading]=useState(false),[progress,setProgress]=useState(""),[downloadPct,setDownloadPct]=useState<number|null>(null),[downloadFile,setDownloadFile]=useState(""),[rows,setRows]=useState<any[]>([]),[error,setError]=useState("");
 async function run(){setLoading(true);setRows([]);setError("");setDownloadPct(null);setDownloadFile("");const onProgress=(p:any)=>{if(p?.file)setDownloadFile(String(p.file).split("/").pop()||p.file);if(p?.status==="progress"){if(typeof p.progress==="number")setDownloadPct(Math.round(p.progress));else if(typeof p.loaded==="number"&&typeof p.total==="number"&&p.total>0)setDownloadPct(Math.round(p.loaded/p.total*100));}if(p?.status==="ready")setDownloadPct(100)};try{
  setProgress("Loading local Gemma…");let generator:any;let backend="WebGPU";
  try{generator=await pipeline("text-generation",MODEL,{device:"webgpu",dtype:"fp32",progress_callback:onProgress});}catch(webgpuError:any){backend="WASM";setProgress("WebGPU failed — loading quantized WASM fallback…");try{generator=await pipeline("text-generation",MODEL,{device:"wasm",dtype:"q8",progress_callback:onProgress});}catch(wasmError:any){throw new Error("Gemma model initialization failed. WebGPU: "+(webgpuError?.message||webgpuError)+" | WASM: "+(wasmError?.message||wasmError));}}
  const out:any[]=[];
  for(let i=0;i<cases.length;i++){const item=cases[i];setProgress("Case "+(i+1)+"/"+cases.length+" · JEV + Gemma ("+backend+")");
   const jt=performance.now();const jp=fetch("/api/evaluate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({state:item.text,questions:[makeQuestion(item)]})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"JEV request failed");const a=j.result?.answers?.outcome;const answer=String(a?.choice||"");return{answer,latencyMs:j.latencyMs??Math.round(performance.now()-jt),valid:item.labels.includes(answer),confidence:a?.probabilities?.[answer]}}).catch((e:any)=>({answer:"ERROR",latencyMs:Math.round(performance.now()-jt),valid:false,error:e.message}));
   const gt=performance.now();const prompt="Allowed labels: "+item.labels.join(", ")+".\
Evidence: "+item.text+"\
Return exactly one allowed label and nothing else.";const gp=generator(prompt,{max_new_tokens:10,do_sample:false,return_full_text:false}).then((g:any)=>{const raw=String(g?.[0]?.generated_text||"");const answer=parseGemma(raw,item.labels);return{answer,latencyMs:Math.round(performance.now()-gt),valid:item.labels.includes(answer)}}).catch((e:any)=>({answer:"ERROR",latencyMs:Math.round(performance.now()-gt),valid:false,error:e.message}));
   const [jev,gemma]=await Promise.all([jp,gp]);out.push({...item,jev,gemma});setRows([...out]);
  }
 }catch(e:any){setError(e?.message||String(e))}finally{setLoading(false);setProgress("");setDownloadPct(null);setDownloadFile("")}}
 const score=(engine:string)=>rows.filter(r=>r[engine]?.answer===r.expected).length;const valid=(engine:string)=>rows.filter(r=>r[engine]?.valid).length;const avg=(engine:string)=>rows.length?Math.round(rows.reduce((n,r)=>n+(r[engine]?.latencyMs||0),0)/rows.length):0;
 return <section className="gemmaBench"><div className="deepIntro"><div className="eyebrow">HEAD-TO-HEAD · IDENTICAL EVIDENCE · IDENTICAL LABEL SPACE</div><h2>JEV vs local Gemma</h2><p>Both engines receive the same evidence and allowed outcomes. Ground truth is declared before execution. Compare exact-label accuracy, output validity and inference latency; JEV additionally exposes selected-label probability.</p></div><div className="compareArch"><div><b>JEV</b><span>server → hosted JEV</span><small>typed Choice · probabilities · API latency</small></div><div><b>Gemma 3 270M</b><span>browser → WebGPU fp32 / WASM q8</span><small>generated label · local latency</small></div></div><button className="run" disabled={loading} onClick={run}>{loading?(progress||"Running…"):"Run head-to-head benchmark →"}</button>{loading&&downloadPct!==null&&<div className="modelDownload"><div><span>{downloadFile||"model"}</span><b>{downloadPct}%</b></div><progress max="100" value={downloadPct}/></div>}{error&&<div className="error">{error}</div>}{rows.length>0&&<><div className="benchmarkSummary"><div><small>JEV EXACT</small><b>{score("jev")} / {rows.length}</b><span>{valid("jev")} valid · {avg("jev")} ms avg</span></div><div><small>GEMMA EXACT</small><b>{score("gemma")} / {rows.length}</b><span>{valid("gemma")} valid · {avg("gemma")} ms avg</span></div></div><div className="benchmarkTable"><div className="benchmarkHeader"><b>Case / truth</b><b>JEV</b><b>Local Gemma</b></div>{rows.map(r=><div className="benchmarkRow" key={r.id}><div><small>{r.title}</small><strong>{r.expected}</strong></div><div className={r.jev.answer===r.expected?"benchPass":"benchFail"}><strong>{r.jev.answer}</strong><span>{r.jev.valid?"valid":"INVALID"} · {r.jev.latencyMs} ms{typeof r.jev.confidence==="number"?" · "+Math.round(r.jev.confidence*100)+"%":""}</span></div><div className={r.gemma.answer===r.expected?"benchPass":"benchFail"}><strong>{r.gemma.answer}</strong><span>{r.gemma.valid?"valid":"INVALID"} · {r.gemma.latencyMs} ms</span></div></div>)}</div></>}<p className="benchmarkNote">Exact match is against declared synthetic cases, not a general model-quality score. Model download is outside Gemma per-case latency; device/browser performance still affects it. JEV latency includes the API path.</p></section>
}