import {Question,Risk} from "./types";
export type DeepCase={id:string;title:string;state:string;expected:"AUTOMATE"|"REVIEW"|"ESCALATE";expectation:string;mutation?:string};
export type DeepSuite={id:string;domain:string;title:string;decision:string;risk:Risk;questions:Question[];policy:string;authority:string;action:string;cases:DeepCase[]};
const questions=(s:string):Question[]=>[
{id:"path",type:"choice",instructions:"Select governance path for "+s+".",criteria:{AUTOMATE:"Inside delegated authority with sufficient evidence and controls.",REVIEW:"Material ambiguity or incomplete evidence requires accountable review.",ESCALATE:"Hard policy, authority or high-consequence condition requires escalation."}},
{id:"risk_contained",type:"noul",instructions:"Probability material risk is adequately contained for "+s+"."},
{id:"evidence_quality",type:"score",instructions:"Score decision evidence quality.",criteria:["completeness","specificity","freshness","independence"]}];
export const deepSuites:DeepSuite[]=[
{id:"architecture-exception",domain:"Architecture",title:"Architecture exception",decision:"Can a standards exception proceed, and under whose authority?",risk:"High",questions:questions("architecture exception"),policy:"AUTOMATE only when containment ≥90%, first exception, compensating controls verified and authority delegated. Repeat exceptions or regulated-control uncertainty → ESCALATE.",authority:"Architecture policy owner; ARB for repeat/material exceptions.",action:"Record exception, owner, expiry and remediation; otherwise create ARB case.",cases:[
{id:"ae1",title:"First, bounded exception",state:"Internal reporting service requests a 90-day secrets-management exception. No PCI data. Compensating HSM control verified by Security. Migration funded, owner named, expiry set. No previous exception.",expected:"AUTOMATE",expectation:"Bounded, reversible, verified first exception inside delegated policy."},
{id:"ae2",title:"Repeat regulated exception",state:"Card payment service requests another 12-month secrets-management exception. PCI scope. Dual authorization and isolation exist. Migration funded, but exception has already been extended once.",expected:"ESCALATE",expectation:"Repeat exception crosses delegated authority even with strong controls.",mutation:"Change repeat extension to first 90-day exception."},
{id:"ae3",title:"Conflicting control evidence",state:"Customer platform requests six months. Service owner says compensating controls are complete; latest Security assessment says two controls remain untested.",expected:"REVIEW",expectation:"Conflicting evidence prevents autonomous disposition."}]},
{id:"release-gate",domain:"Engineering",title:"Production release gate",decision:"Should this change ship under delegated release authority?",risk:"High",questions:questions("production release"),policy:"Material releases require tested rollback and observability. Missing rollback on customer/payment path → ESCALATE. Low-impact reversible changes with complete evidence may AUTOMATE.",authority:"Release policy; change authority for exceptions.",action:"Deploy, request review, or stop release and create exception.",cases:[
{id:"rg1",title:"Routine reversible release",state:"Internal reporting UI change. No transaction path. Canary passed, rollback tested, SLO dashboards present, required tests green.",expected:"AUTOMATE",expectation:"Low consequence, reversible and fully evidenced."},
{id:"rg2",title:"Payment change, no rollback",state:"Payment authorization change affects 35% of card traffic. Tests green and observability present, but rollback untested and schema migration is one-way.",expected:"ESCALATE",expectation:"Material blast radius plus non-reversibility violates release policy.",mutation:"Add tested rollback and reversible migration."},
{id:"rg3",title:"Observability gap",state:"Customer onboarding release. Rollback tested and functional tests green. New asynchronous failure path has no alert or production SLO signal.",expected:"REVIEW",expectation:"Control coverage is incomplete."}]},
{id:"agent-action",domain:"AI Governance",title:"Autonomous agent authority",decision:"May an enterprise agent execute the proposed action without human approval?",risk:"High",questions:questions("autonomous agent action"),policy:"AUTOMATE only reversible scoped actions inside explicit delegation. External commitments, money movement, destructive changes or authority ambiguity → ESCALATE.",authority:"Accountable human owner defines delegation envelope.",action:"Execute with audit record, queue approval, or deny/escalate.",cases:[
{id:"aa1",title:"Draft an ADR",state:"Architecture agent will create a draft ADR in a feature branch using approved templates. No merge, external communication, production access or irreversible action.",expected:"AUTOMATE",expectation:"Reversible draft inside narrow delegated scope."},
{id:"aa2",title:"Accept supplier commitment",state:"Procurement agent proposes accepting a supplier renewal creating a 24-month €420k commitment. It can click acceptance. No human approval recorded.",expected:"ESCALATE",expectation:"Agent lacks authority for material external commitment."},
{id:"aa3",title:"Incomplete runbook precondition",state:"Ops agent proposes restarting a degraded service. Runbook allows restart after two health checks, but only one check is available.",expected:"REVIEW",expectation:"Potentially legitimate action but precondition evidence is incomplete."}]},
{id:"context-admission",domain:"Knowledge",title:"Context admission",decision:"Does this evidence deserve scarce operative agent context?",risk:"Medium",questions:questions("context admission"),policy:"Admit current, decision-relevant, authoritative evidence. Contradictory/provenance-poor claims → REVIEW; known superseded material → ESCALATE from operative context.",authority:"Context policy and knowledge steward.",action:"Admit, verify/compress, or exclude.",cases:[
{id:"ca1",title:"Authoritative ADR",state:"Signed ADR from yesterday directly governs the service being modified. Source is system of record and explicitly supersedes prior ADR.",expected:"AUTOMATE",expectation:"Authoritative, fresh and directly relevant."},
{id:"ca2",title:"Unverified meeting claim",state:"Meeting notes say Security approved the pattern but contain no approver or decision ID. Security policy repository still marks it restricted.",expected:"REVIEW",expectation:"Provenance conflicts with authoritative state."},
{id:"ca3",title:"Superseded wiki policy",state:"Three-year-old copied wiki page recommends an authentication pattern explicitly deprecated by the current signed standard.",expected:"ESCALATE",expectation:"Known stale material must not enter operative context."}]},
{id:"requirements",domain:"SDLC",title:"Requirement readiness",decision:"Is an idea sufficiently specified to enter autonomous implementation?",risk:"Medium",questions:questions("requirement readiness"),policy:"AUTOMATE only with testable outcomes, constraints, ownership and impacted architecture. Material ambiguity → REVIEW; missing authority/compliance constraints → ESCALATE.",authority:"Product owner plus architecture/control owners.",action:"Generate work package, request clarification, or initiate governance discovery.",cases:[
{id:"rr1",title:"Implementation-ready",state:"Add account nickname editing. Acceptance criteria define validation, API behavior, audit event and accessibility. Product owner, service and data owner identified. No new sensitive data.",expected:"AUTOMATE",expectation:"Testable scope and ownership are explicit."},
{id:"rr2",title:"Vague AI ambition",state:"Request: Use AI to improve customer onboarding and reduce friction. No target metric, process boundary, data scope, accountable owner or regulatory constraints.",expected:"REVIEW",expectation:"Valid idea, not yet implementable."},
{id:"rr3",title:"Regulated authority unknown",state:"Change automated credit-decision logic. Functional criteria exist, but model-risk classification, legal basis and accountable credit-policy owner are unknown.",expected:"ESCALATE",expectation:"Regulated authority and controls must be established first."}]},
{id:"data-incident",domain:"Data",title:"Critical data-quality incident",decision:"Can the anomaly be corrected automatically or must accountable owners intervene?",risk:"High",questions:questions("data-quality incident"),policy:"Regulatory/customer reporting impact or unknown lineage → ESCALATE. Known-source contained anomaly with verified correction may AUTOMATE.",authority:"Data owner; regulatory reporting owner for material impact.",action:"Correct/quarantine, launch lineage analysis, or escalate.",cases:[
{id:"dq1",title:"Contained duplicate batch",state:"Known ETL retry duplicated 0.3% of non-regulatory analytics rows. Batch ID identifies all duplicates. Correction tested against reconciliation totals. No downstream decisions consumed batch.",expected:"AUTOMATE",expectation:"Cause, scope, correction and non-impact are evidenced."},
{id:"dq2",title:"Regulatory lineage uncertainty",state:"Capital reporting attribute shows unexplained 4.8% shift. Upstream source changed yesterday. Lineage has two undocumented transformations and filing cutoff is tomorrow.",expected:"ESCALATE",expectation:"Material reporting impact plus unknown lineage."},
{id:"dq3",title:"Conflicting reconciliations",state:"Customer master reconciliation passes aggregate but fails one legal-entity segment. Two sources disagree on effective-date semantics.",expected:"REVIEW",expectation:"Evidence is insufficient to select a correction safely."}]},
{id:"investment",domain:"Strategy",title:"Investment continuation",decision:"Should the next funding tranche proceed based on outcome evidence?",risk:"Medium",questions:questions("investment continuation"),policy:"Continue when outcome evidence is credible and indicators meet agreed bounds. Thesis invalidation/material scope change → ESCALATE.",authority:"Initiative owner; portfolio committee for thesis change.",action:"Release tranche, commission evidence, or reopen portfolio decision.",cases:[
{id:"iv1",title:"Outcome supports tranche",state:"Automation initiative is 5% over delivery plan but achieved 18% handling-time reduction against 15% target. Benefits independently validated; next tranche budgeted.",expected:"AUTOMATE",expectation:"Outcome thesis holds inside tolerance."},
{id:"iv2",title:"Outputs, no outcomes",state:"Transformation delivered 92% of features and spent 80% of budget. Adoption is 14% against 60% target and no business outcome improved after two quarters.",expected:"ESCALATE",expectation:"Delivery output no longer supports investment thesis."},
{id:"iv3",title:"Promising weak evidence",state:"Pilot shows 25% productivity gain in one team, but sample is 12 users over three weeks and self-reported. Expansion triples spend.",expected:"REVIEW",expectation:"Promising signal, inadequate evidence for automatic scale-up."}]},
{id:"accountability",domain:"Organization",title:"Accountability gap",decision:"Is there sufficient accountable authority for this cross-domain decision?",risk:"Medium",questions:questions("accountability assignment"),policy:"AUTOMATE routing when exactly one accountable role owns the decision. Conflicting/no accountability → ESCALATE governance.",authority:"Operating model / executive delegation.",action:"Route decision, confirm owner, or create accountability-resolution case.",cases:[
{id:"ac1",title:"Clear delegated owner",state:"Customer Identity capability map names Head of Identity accountable for authentication policy; Security is consulted. Requested change is inside that scope.",expected:"AUTOMATE",expectation:"Single accountable role and explicit consultation path."},
{id:"ac2",title:"Two accountable owners",state:"Operating model marks both Digital Channels and Customer Security Accountable for authentication exceptions. No tie-break authority is defined.",expected:"ESCALATE",expectation:"Conflicting accountability invalidates autonomous decision."},
{id:"ac3",title:"Stale ownership",state:"Data product lists an accountable owner who left last month. Acting manager exists in HR but delegation for data decisions is not recorded.",expected:"REVIEW",expectation:"Likely successor exists but formal authority is unclear."}]}
];