import {Question} from "./types";
export const fundProspectusCase={
 excerpt:"Northstar Global Opportunities SICAV is an open-ended investment company organised as a société d’investissement à capital variable under Luxembourg law and qualifies as an undertaking for collective investment in transferable securities. The Company is constituted as an umbrella fund with its registered office at 14, rue du Marché, L-1234 Luxembourg. Aurora Management Company S.A., 8 boulevard Royal, L-2449 Luxembourg, has been appointed as management company and has delegated portfolio management for the Global Equity Sub-Fund to Meridian Asset Management Ltd, 20 Bishopsgate, London EC2N, while retaining oversight. Continental Depositary Bank S.A., 2 avenue de la Gare, L-1610 Luxembourg, has been appointed depositary and custodian of the assets. Atlas Fund Services (Luxembourg) S.A., 5 rue Goethe, L-1637 Luxembourg, acts as central administrator, registrar and transfer agent. Renaud & Partners S.à r.l., 11 route d'Esch, L-1470 Luxembourg, is the approved statutory auditor. The Commission de Surveillance du Secteur Financier (CSSF) is the competent supervisory authority.",
 judgmentState:"Read the raw prospectus excerpt below. Do not assume any pre-extracted entities. Identify which legal entity is described as fulfilling each requested role. Answer only from the text; if the role is not evidenced, select NOT_EVIDENCED. PROSPECTUS EXCERPT: ",
 questions:[
 {id:"management_company",type:"choice",instructions:"Which legal entity is explicitly appointed as management company?",criteria:{"Aurora Management Company S.A.":"Text explicitly appoints it.","Meridian Asset Management Ltd":"Only if explicitly appointed to this role.","Continental Depositary Bank S.A.":"Only if explicitly appointed to this role.","Atlas Fund Services (Luxembourg) S.A.":"Only if explicitly appointed to this role.","Renaud & Partners S.à r.l.":"Only if explicitly appointed to this role.","NOT_EVIDENCED":"No entity is evidenced for the role."}},
 {id:"investment_manager",type:"choice",instructions:"Which legal entity performs delegated portfolio management?",criteria:{"Aurora Management Company S.A.":"Only if text says it performs delegated portfolio management.","Meridian Asset Management Ltd":"Text explicitly identifies the delegate.","Continental Depositary Bank S.A.":"Only if evidenced.","Atlas Fund Services (Luxembourg) S.A.":"Only if evidenced.","Renaud & Partners S.à r.l.":"Only if evidenced.","NOT_EVIDENCED":"No entity is evidenced for the role."}},
 {id:"depositary",type:"choice",instructions:"Which legal entity is explicitly appointed depositary?",criteria:{"Aurora Management Company S.A.":"Only if evidenced.","Meridian Asset Management Ltd":"Only if evidenced.","Continental Depositary Bank S.A.":"Text explicitly appoints it.","Atlas Fund Services (Luxembourg) S.A.":"Only if evidenced.","Renaud & Partners S.à r.l.":"Only if evidenced.","NOT_EVIDENCED":"No entity is evidenced for the role."}},
 {id:"administrator",type:"choice",instructions:"Which legal entity acts as central administrator?",criteria:{"Aurora Management Company S.A.":"Only if evidenced.","Meridian Asset Management Ltd":"Only if evidenced.","Continental Depositary Bank S.A.":"Only if evidenced.","Atlas Fund Services (Luxembourg) S.A.":"Text explicitly identifies it.","Renaud & Partners S.à r.l.":"Only if evidenced.","NOT_EVIDENCED":"No entity is evidenced for the role."}},
 {id:"auditor",type:"choice",instructions:"Which legal entity is the approved statutory auditor?",criteria:{"Aurora Management Company S.A.":"Only if evidenced.","Meridian Asset Management Ltd":"Only if evidenced.","Continental Depositary Bank S.A.":"Only if evidenced.","Atlas Fund Services (Luxembourg) S.A.":"Only if evidenced.","Renaud & Partners S.à r.l.":"Text explicitly identifies it.","NOT_EVIDENCED":"No entity is evidenced for the role."}}
 ] as Question[],
 graphRows:[
 {from:"Northstar SICAV",relation:"managed by",question:"management_company"},
 {from:"Global Equity Sub-Fund",relation:"portfolio managed by",question:"investment_manager"},
 {from:"Northstar SICAV",relation:"depositary",question:"depositary"},
 {from:"Northstar SICAV",relation:"administered by",question:"administrator"},
 {from:"Northstar SICAV",relation:"audited by",question:"auditor"}]
};